name: Performance Test against Tags
on:
  workflow_dispatch:
    inputs:
      startTag:
        description: 'Tag to begin with'
        required: true
        default: '5.9.2'
        type: string
      endTag:
        description: 'Tag to end with'
        required: false
        type: string
        default: '5.8.1'

jobs:
  determine-tag-range:
    runs-on: ubuntu-latest
    steps:
      - name: Get the Repo
        uses: actions/checkout@v2
      - name: Verify tags
        run: |
          git fetch --unshallow --tags
          git tag -l
          if [ ! $(git tag -l "${{ github.event.inputs.startTag }}") ]; then
            echo "::error::The start tag you've requested does not exist. Verify the tag you've requested - ${{ github.event.inputs.startTag }} - exists."
            exit 1
          fi

          if [ ! $(git tag -l "${{ github.event.inputs.endTag }}") ]; then
            echo "::error::The end tag you've requested does not exist. Verify the tag you've requested - ${{ github.event.inputs.startTag }} -  exists."
            exit 1
          fi
      - name: determine direction
        id: determineDirection
        run: |
          begin=$(printf '%s\n%s\n' "${{ github.event.inputs.startTag }}" "${{ github.event.inputs.endTag }}" | sort -V | head -n 1)
          if [[ "${begin}" == "${{ github.event.inputs.startTag }}" ]]; then
            start="${{ github.event.inputs.startTag }}"
            end="${{ github.event.inputs.endTag }}"
          else
            start="${{ github.event.inputs.endTag }}"
            end="${{ github.event.inputs.startTag }}"
          fi
          echo "::notice::You told me to start with ${{ github.event.inputs.startTag }}"
          echo "::notice::I'm going to start with ${start}"
          echo "::set-output name=startWith::${start}"
          echo "::notice::You told me to end with ${{ github.event.inputs.endTag }}"
          echo "::notice::I'm going to end with ${end}"
          echo "::set-output name=endWith::${end}"

      - name: get tag list
        id: taglist
        run: |
          start="${{ steps.determineDirection.outputs.startWith }}"
          end="${{ steps.determineDirection.outputs.endWith }}"
          additionalTags=$(git tag -l | sed -n "/${start}/,/${end}/p");
          echo "list: ${additionalTags}"
          additionalTags="${additionalTags//'%'/'%25'}"
          additionalTags="${additionalTags//$'\n'/'%0A'}"
          additionalTags="${additionalTags//$'\r'/'%0D'}"
          echo "::setputput name=processTags::${addtionalTags}"
          #git tag -l | sed -n '/5.9.0/,/5.8.0/p'
      - name: activate each tag
        id: activate-tags
        run: |
          #tags="${{ steps.taglist.outputs.tagList }}"
          while IFS= read -r tag; do
              echo "::notice::The tag we need to activate is ${tag}"
          done <<< "${{ steps.taglist.output.processTags }}"

